//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationContentType", Namespace="https://mnotify.gov.md")]
    public enum NotificationContentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Html = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationRequest", Namespace="https://mnotify.gov.md")]
    public partial class NotificationRequest : object
    {
        
        private ServiceReference.NotificationContent[] ContentsField;
        
        private string[] CopyRecipientsField;
        
        private string[] HiddenRecipientsField;
        
        private ServiceReference.NotificationImportance ImportanceField;
        
        private string[] RecipientsField;
        
        private string SenderField;
        
        private bool SeparateRecipientsField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference.NotificationContent[] Contents
        {
            get
            {
                return this.ContentsField;
            }
            set
            {
                this.ContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] CopyRecipients
        {
            get
            {
                return this.CopyRecipientsField;
            }
            set
            {
                this.CopyRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] HiddenRecipients
        {
            get
            {
                return this.HiddenRecipientsField;
            }
            set
            {
                this.HiddenRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.NotificationImportance Importance
        {
            get
            {
                return this.ImportanceField;
            }
            set
            {
                this.ImportanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Recipients
        {
            get
            {
                return this.RecipientsField;
            }
            set
            {
                this.RecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool SeparateRecipients
        {
            get
            {
                return this.SeparateRecipientsField;
            }
            set
            {
                this.SeparateRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationContent", Namespace="https://mnotify.gov.md")]
    public partial class NotificationContent : object
    {
        
        private ServiceReference.NotificationAttachment[] AttachmentsField;
        
        private string ContentField;
        
        private string LanguageField;
        
        private string SubjectField;
        
        private ServiceReference.NotificationContentType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.NotificationAttachment[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference.NotificationContentType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationImportance", Namespace="https://mnotify.gov.md")]
    public enum NotificationImportance : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationAttachment", Namespace="https://mnotify.gov.md")]
    public partial class NotificationAttachment : object
    {
        
        private byte[] ContentField;
        
        private string IDField;
        
        private string NameField;
        
        private string TypeField;
        
        private string UriField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Uri
        {
            get
            {
                return this.UriField;
            }
            set
            {
                this.UriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationStatus", Namespace="https://mnotify.gov.md")]
    public partial class NotificationStatus : object
    {
        
        private ServiceReference.NotificationChannelStatus[] ChannelStatusField;
        
        private ServiceReference.NotificationDeliveryStatus GeneralStatusField;
        
        private string RecipientField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ServiceReference.NotificationChannelStatus[] ChannelStatus
        {
            get
            {
                return this.ChannelStatusField;
            }
            set
            {
                this.ChannelStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference.NotificationDeliveryStatus GeneralStatus
        {
            get
            {
                return this.GeneralStatusField;
            }
            set
            {
                this.GeneralStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Recipient
        {
            get
            {
                return this.RecipientField;
            }
            set
            {
                this.RecipientField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationChannelStatus", Namespace="https://mnotify.gov.md")]
    public partial class NotificationChannelStatus : object
    {
        
        private ServiceReference.NotificationDeliveryChannel ChannelField;
        
        private ServiceReference.NotificationDeliveryStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference.NotificationDeliveryChannel Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference.NotificationDeliveryStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationDeliveryStatus", Namespace="https://mnotify.gov.md")]
    public enum NotificationDeliveryStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationDeliveryChannel", Namespace="https://mnotify.gov.md")]
    public enum NotificationDeliveryChannel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://mnotify.gov.md", ConfigurationName="ServiceReference.IMNotify")]
    public interface IMNotify
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://mnotify.gov.md/IMNotify/PostSimpleNotification", ReplyAction="https://mnotify.gov.md/IMNotify/PostSimpleNotificationResponse")]
        System.Threading.Tasks.Task<string> PostSimpleNotificationAsync(string type, string sender, string recipient, string subject, ServiceReference.NotificationContentType contentType, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://mnotify.gov.md/IMNotify/PostNotificationRequest", ReplyAction="https://mnotify.gov.md/IMNotify/PostNotificationRequestResponse")]
        System.Threading.Tasks.Task<string> PostNotificationRequestAsync(ServiceReference.NotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://mnotify.gov.md/IMNotify/GetNotificationStatus", ReplyAction="https://mnotify.gov.md/IMNotify/GetNotificationStatusResponse")]
        System.Threading.Tasks.Task<ServiceReference.NotificationStatus[]> GetNotificationStatusAsync(string notificationID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMNotifyChannel : ServiceReference.IMNotify, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MNotifyClient : System.ServiceModel.ClientBase<ServiceReference.IMNotify>, ServiceReference.IMNotify
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MNotifyClient() : 
                base(MNotifyClient.GetDefaultBinding(), MNotifyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMNotify.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MNotifyClient(EndpointConfiguration endpointConfiguration) : 
                base(MNotifyClient.GetBindingForEndpoint(endpointConfiguration), MNotifyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MNotifyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MNotifyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MNotifyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MNotifyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MNotifyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> PostSimpleNotificationAsync(string type, string sender, string recipient, string subject, ServiceReference.NotificationContentType contentType, string content)
        {
            return base.Channel.PostSimpleNotificationAsync(type, sender, recipient, subject, contentType, content);
        }
        
        public System.Threading.Tasks.Task<string> PostNotificationRequestAsync(ServiceReference.NotificationRequest request)
        {
            return base.Channel.PostNotificationRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.NotificationStatus[]> GetNotificationStatusAsync(string notificationID)
        {
            return base.Channel.GetNotificationStatusAsync(notificationID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMNotify))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMNotify))
            {
                return new System.ServiceModel.EndpointAddress("https://mnotify.gov.md:8443/MNotify.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MNotifyClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMNotify);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MNotifyClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMNotify);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMNotify,
        }
    }
}
